apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pretalx.fullname" . }}
  labels:
    {{- include "pretalx.stdlabels" . | nindent 4 }}
data:
  pretalx.cfg: |-
    {{- tpl (.Files.Get "config/pretalx.cfg") . | nindent 4 }}
