apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pretalx.fullname" . }}
  labels:
    {{- include "pretalx.stdlabels" . | nindent 4 }}
type: Opaque
data:
  pretalx-db-pass: {{ default "" .Values.database.password | b64enc | quote }}
  pretalx-mail-password: {{ default "" .Values.mail.password | b64enc | quote }}
