apiVersion: v1
kind: Service
metadata:
  name: {{ include "pretalx.fullname" . }}
  labels:
    {{- include "pretalx.stdlabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pretalx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
